#!/usr/bin/env python3

# qrencode GUI tool.

from gettext import gettext as _
from gi.repository import Gtk

from qrencodegui.Config import *
from qrencodegui.Handler import Handler

def main():
    builder = Gtk.Builder()
    builder.add_from_file(GLADE)
    builder.connect_signals(Handler(builder))
    win = builder.get_object('main_window')
    win.show_all()
    Gtk.main()

if __name__ == '__main__':
    main()
