#!/usr/bin/env python3

# qrencode GUI tool.

from gettext import gettext as _
from gi.repository import Gtk

from qrencodegui import Config
from qrencodegui.Handler import Handler

def main():
    builder = Gtk.Builder()
    for glade in Config.GLADE_FILES:
        builder.add_from_file(glade)

    handler = Handler(builder)
    builder.connect_signals(handler)
    handler.run()

if __name__ == '__main__':
    main()
